### ISSUE TITLE
星星需要切成圖片

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/LiYuanEgg#7]
![image](https://cloud.githubusercontent.com/assets/4414580/7344319/1e4c26e4-ecfd-11e4-8b4b-08095f01c80c.png)

**Comment by maysheena** [comment]
已經換上去囉～

![2015-04-28 20 37 36](https://cloud.githubusercontent.com/assets/11195240/7369712/b5c83aa0-ede6-11e4-9ed4-73e0264acbbb.png)
